2404-geekcamp/main

README.md, app/controllers/UserController.js, babel.config.js, client/src/App.test.js, package-lock.json, package.json, tests/app/controllers/UserController.test.js
#10 を実装
テストの作成（UserController.test.js）
=> #10: ユーザの評価関数を実装

README.md
追加でsupabaseのタイムゾーンをAsia/Tokyoに変更
=> 12 kodai feature

server/config/routes/index.js, server/controllers/UserController.js, server/db.js, server/express.js, server/models/UserModel.js
=> コネクションプール接続になるよう修正

server/app/controllers/ChatController.js, server/app/models/ChatModel.js, server/config/routes/index.js, server/tests/rest/chat/create.http
=> #38: チャットを新しく作成する関数を実装した

client/src/App.css, client/src/pages/auth/SignUp.jsx, client/src/styles/SignUp.css, client/src/styles/global.css
figmaのデザイン通りにした
ユーザー名とメールアドレスとパスワードはuseStateで状態管理している
認証機能はまだ実装していない
=> 28 popo feature

client/src/index.css, client/src/pages/auth/SignUp.jsx, client/src/styles/global.css, client/tailwind.config.js
=> signup cssとtailwindcss のstyleが当たるように修正

README.md
#32 
`invite_messages` に `is_checked`を追加
追加用クエリ
```sql
ALTER TABLE invite_messages ADD COLUMN is_checked BOOLEAN DEFAULT false;
```
=> add: invite_messages.is_checked

server/app/controllers/InviteMessageController.js, server/app/models/InviteMessageModel.js, server/config/routes/index.js, server/tests/rest/invite_message/create.http
#30 
`invite_messages`に対する POST を処理
=> #30: 招待メッセージを新しく作成する関数を実装した

server/app/controllers/JoinController.js, server/app/models/JoinModel.js, server/config/routes/index.js, server/tests/rest/join/insert.http
#39 
` /chat/:chat_id/user/:user_id/joins/create` への POST によって作成
=> #39: チャットに新しくユーザーを追加する関数を実装した

server/app/controllers/ChatHistoryController.js, server/app/models/ChatHistoryModel.js, server/config/routes/index.js, server/tests/rest/chat_history/fetch.http
#40 
`/chat/:chat_id/histories` への POST
=> #40: チャットidを受け取り、チャット履歴の一覧を返す関数を実装した

server/app/controllers/ChatHistoryController.js, server/app/models/ChatHistoryModel.js, server/config/routes/index.js, server/tests/rest/chat_history/insert.http
#41 
`/chat/:chat_id/histories/create` に POST
=> #41: チャットを送信する関数を実装した

server/app/controllers/SkillController.js, server/app/models/SkillModel.js, server/config/routes/index.js, server/tests/rest/skill/fetch_all.http
=> #34 技術一覧を取得する関数を実装した

server/app/controllers/ExperienceOptionController.js, server/app/models/ExperienceOptionModel.js, server/config/routes/index.js, server/tests/rest/experience_option/fetch_all.http
#35 
`/experience_options` への GET
=> #35: ハッカソンの経験一覧を選択肢として取得する関数を実装した

server/app/controllers/StanceOptionController.js, server/app/models/StanceOptionModel.js, server/config/routes/index.js, server/tests/rest/stance_option/fetch_all.http
=> #36: ハッカソンへのスタンス一覧の選択肢を取得する関数を実装した

client/.env.sample, client/.gitignore, client/package-lock.json, client/package.json, client/src/pages/search/Search.jsx
#76 
検索画面のコンポーネントに注入するデータを、axiosによるAPIサーバへのfetch で実装した
=> #76: 検索画面を作成した

client/src/App.jsx, client/src/pages/search/Result.jsx
=> 検索結果の要素を作成

client/src/pages/InviteMessagePreview.jsx
Modal.setAppElement('#root');を忘れてたので追加
=> エラーの解消&「出る」を「話してみる」に変更

client/src/components/Header.jsx, client/src/pages/Home.jsx
propsに
props.backPath
props.back
props.forWardPath
props.forward
を指定するとそのページへ飛べる
=> header 要素完成

client/src/pages/UserId.jsx
currentUserがtrueで編集ボタン、falseで招待メッセージボタンになるようにボタンも作成
=> 招待メッセージ作成モーダル

client/src/pages/UserId.jsx, client/src/pages/UserIdEdit.jsx, client/src/pages/chats/Chats.jsx, client/src/pages/chats/ChatsId.jsx, client/src/pages/search/Result.jsx, client/src/pages/search/Search.jsx
ヘッダーが必要だと思われるページにヘッダーを追加しました
元々あった要素だけの時に画面ちょうどにcssあてててもスクロールできるようになっている可能性が高いです
=> ヘッダーが必要なページにヘッダーを追加
